import { UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const { data: posts } = api.posts.getAll.useQuery();
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>{user.isSignedIn ? user.user.firstName : ""}</p>
        {posts?.map(post => {
          return (
            <p key={post.id}>{post.content}</p>
          )
        })}
        <UserButton afterSignOutUrl="/" />
      </main>
    </>
  );
}
